### ISSUE TITLE
Fix wrong SVGs 

### ISSUE THREAD

**Issue by Michael5601** [eclipse-platform/eclipse.platform.images#101]
As part of my analysis for introducing vector graphics in Eclipse, I discovered several SVGs that either contain issues or do not align with their corresponding PNGs. Fortunately, all these issues can be resolved by adjusting the SVG files themselves, eliminating the need for a pull request outside the `eclipse.platform.images` repository.

The following SVGs are problematic:

1. **pinned_ovr.svg** in `org.eclipse.e4.ui.workbench.renderers.swt`:
   - The PNG version is a different icon from the SVG. Upon opening the SVG in Inkscape, three distinct icons are displayed—one matches the PNG, while another is the one shown in the SVG. The current image area is set to display the SVG icon. The SVG needs to be changed so that the correct icon is in the image area and the others are deleted.
   
   **PNG:**
   ![pinned_ovr](https://github.com/user-attachments/assets/76afc9ee-fc75-4ea7-be05-e6fa23cc93e6)
   
   **SVG:**
   ![pinned_ovr2](https://github.com/user-attachments/assets/da511362-73cb-4128-84b1-19d790c6338c)
   
   **SVG opened in Inkscape:**
   ![three icons](https://github.com/user-attachments/assets/6fc20d42-54fa-4564-99a0-ae607a0bcbee)

2. **build_exec.svg** in `org.eclipse.pde.ui\icons\etool16` and its duplicate in `org.eclipse.ui.ide\icons\full\etool16`:
   - When opening either of these SVGs in Inkscape, you’ll notice that the text isn't converted to a path. As a result, different rasterizers will render the text using default fonts, leading to inconsistencies. This can be fixed by converting the text to a path with a single click. I dont know if there are other duplicates with a different name that have the same issue because these two Icons differ slightly so the duplicates can't be found by automatically comparing pixel values. However, the duplicate in `org.eclipse.pde.ui\icons\obj16` with the same name does not have this issue.
   
   **Icon displayed in Chrome (or rasterized with Batik):**
   ![image](https://github.com/user-attachments/assets/81d727ad-0f1e-4c7a-9da6-d1c57fce264e)
   
   **SVG opened in Inkscape:**
   ![path](https://github.com/user-attachments/assets/4e078cc6-40a9-44e5-832b-98079a200762)

3. **participant_rem.svg** in `org.eclipse.team.ui\icons\full\elcl16`:
   - When viewed in Inkscape, Chrome, or rasterized with most other rasterizers, the image appears compressed in height compared to the PNG. The PNG fits other SVGs like `rem_co.svg` in `org.eclipse.debug.ui\icons\full\elcl16` and it's duplicate in `org.eclipse.ui.console\icons\full\elcl16`. An easy solution would be to replace `participant_rem.svg` with one of these versions of `rem_co.svg`.
   
   **PNG:**
   ![participant_rem](https://github.com/user-attachments/assets/d9b12837-4ddf-4f91-861e-7886d10c2a86)
   
   **SVG of participant_rem:**
   ![participant_rem2](https://github.com/user-attachments/assets/8be87839-4732-46c4-b899-50f88ea6a064)
   
   **SVG of rem_co:**
   ![rem_co2](https://github.com/user-attachments/assets/43091f46-0c2b-4946-8b45-93bf0d0fcf0a)

The issues with `pinned_ovr`, `build_exec` (including its duplicate), and `participant_rem` are fixed in:  https://github.com/eclipse-platform/eclipse.platform.images/pull/102

**Comment by IamLRBA** [comment]
Hello @Michael5601 , if this issue is still active, i would like to work on if please\.
Thanks!

**Comment by Michael5601** [comment]
> Hello @Michael5601 , if this issue is still active, i would like to work on if please. Thanks!

Hey @IamLRBA I appreciate your help but I already posted a PR that fixes the issue in https://github.com/eclipse-platform/eclipse.platform.images/pull/102. The PR is not yet accepted.

**Comment by IamLRBA** [comment]
Alright @Michael5601, I'll be delighted to help on any other issue if ever you have one.
Thanks!

**Comment by Michael5601** [comment]
> Alright @Michael5601, I'll be delighted to help on any other issue if ever you have one. Thanks!

Hi, I am working on a project to include vector graphics in the icon processing of Eclipse. This enables a project to fix/remake all the icons used in Eclipse as the state of the icons could be improved. If you are interested in graphic design and want a big task in collaboration with the Eclipse UI team, this could be something for you. An improvement of this scope would have huge impact in the Eclipse Community.

**Comment by IamLRBA** [comment]
Wow, that's amazing @Michael5601, I am a graphics design enthusiast and would very much love to be part and contribute to this project. 
Thanks a lot Michael.

**Comment by Michael5601** [comment]
> Wow, that's amazing @Michael5601, I am a graphics design enthusiast and would very much love to be part and contribute to this project. Thanks a lot Michael.

Sounds great to me :) I will open an issue for this topic so we can gather some feedback and maybe split up the task in smaller packages. We also need to find out the requirements for a new set of icons.

**Comment by IamLRBA** [comment]
Thanks so much for the assist @Michael5601
