### ISSUE TITLE
Fix undo / redo icons according to standard

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.images#113]
AFAICS these two icons are also not aligned according to https://github.com/eclipse-platform/eclipse.platform.images/issues/108

@Michael5601 WDYT?

![image](https://github.com/user-attachments/assets/e0602b05-2337-4fb7-b2b6-330a893e1ba5)

**Comment by vogella** [comment]
![image](https://github.com/user-attachments/assets/d0dd8f5b-7156-4a1e-ba6d-5d02ae6a98bf)

**Comment by Michael5601** [comment]
There are many icons that need to be fixed. It's hard to say from your first screenshot if they are not aligned properly. In the second screenshot it is obvious.

I needed 1.5 hours to remake the other two icons and disabled variants and place them into Eclipse. Right now I don't have time to fix all the icons so I focus on only fixing the SVGs that can't be rasterized properly with JSVG as this is directly related with my project. 

I think we should still create issues for the problems just to gather them and get a feeling about how much work it would be.

**Comment by vogella** [comment]
Thanks @BeckerWdf
