### ISSUE TITLE
Incorrect size of org.eclipse.help.ui/icons/obj16/container_obj.png

### ISSUE THREAD

**Issue by 2wendex2** [eclipse-platform/eclipse.platform.images#94]
**Description of the bug**
Icon org.eclipse.help.ui/icons/obj16/container_obj.png has 14x13 size but model object icon should be have 16x16 size. See https://www.eclipse.org/articles/Article-UI-Guidelines/Contents.html#IconSpecsSize_VDG

Because of this that icon looks stretched in the Help view.
![image](https://github.com/user-attachments/assets/da2d229d-53c0-409a-aa86-dbf658fc17b1)

**Possible fixes**
Replace current icon with an icon with size 16x16. Attached a possible new icon:
![container_obj](https://github.com/user-attachments/assets/84255404-cb93-415e-9f00-94f01ce394c6)

**Comment by akurtakov** [comment]
@BeckerWdf Would you be able to look into that one?

**Comment by BeckerWdf** [comment]
> @BeckerWdf Would you be able to look into that one?

Sure

**Comment by BeckerWdf** [comment]
> Icon org.eclipse.help.ui/icons/obj16/topic_small.png has 14x13 size but model object icon should be have 16x16 size

I don't see this. See:
<img width="1336" alt="image" src="https://github.com/user-attachments/assets/16c0d99b-7798-4144-9d34-96a07ee06f5c">

Where do you see the icons stretched? Can you mark it in the screenshot?

**Comment by BeckerWdf** [comment]
> Where do you see the icons stretched? Can you mark it in the screenshot?

Do you mean this one and does this look better to you?
<img width="464" alt="image" src="https://github.com/user-attachments/assets/a38c1bb2-b7a8-4731-95bf-29fd4d8282a3">

**Comment by 2wendex2** [comment]
@BeckerWdf  I made a mistake. I wanted to say about org.eclipse.help.ui/icons/obj16
/container_obj.png

**Comment by BeckerWdf** [comment]
> @BeckerWdf I made a mistake. I wanted to say about org.eclipse.help.ui/icons/obj16/container_obj.png

Ah yes I see. I can fix that. But independent from that issue. What do you think about the drawing in side making topic_small a bit bigger (using topic.png) as shown in my screenshot?

**Comment by 2wendex2** [comment]
> Ah yes I see. I can fix that. But independent from that issue. What do you think about the drawing in side making topic_small a bit bigger (using topic.png) as shown in my screenshot?
I don't think this is a very good idea. I have already tried to resize the icon without stretching or changing it and it looks good.
My icon with changed size: 
![container_obj](https://github.com/user-attachments/assets/012d3081-2dd2-42da-8cac-1c0aede5a280)
Table of contents after changing size of icon: 
![image](https://github.com/user-attachments/assets/6600653b-8aca-4f46-ad17-d66f3382a3a6)

**Comment by BeckerWdf** [comment]
How about this:

<img width="699" alt="Screenshot 2024-09-26 at 13 56 31" src="https://github.com/user-attachments/assets/c04bb5b1-062d-4b84-808e-93b81b71a0f4">

Does it look better?

**Comment by 2wendex2** [comment]
> Does it look better?
No, obj_container icon and obj_container with overlay icon should have the same size. How did you do two variant? Redrawn both icons?

**Comment by BeckerWdf** [comment]
> > Does it look better?
> 
> No, obj_container icon and obj_container with overlay icon should have the same size. How did you do two variant? Redrawn both icons?

I have fix the SVG of obj_contain icon. 
With "obj_contain with overlay" you mean the once e.g. in front of "Basic tutorial"?
This is created by combining obj_contain.png with the overlay icon doc_co.png
like this:

```
		ImageDescriptor base = HelpUIResources
				.getImageDescriptor(IHelpUIConstants.IMAGE_CONTAINER);
		ImageDescriptor ovr = HelpUIResources
				.getImageDescriptor(IHelpUIConstants.IMAGE_DOC_OVR);
		ImageDescriptor desc = new OverlayIcon(base,
				new ImageDescriptor[][] { { ovr } });
		containerWithTopicImage = desc.createImage();
```

So shouldn't they have the same size then?

**Comment by BeckerWdf** [comment]
> Try to just replace obj_container icon on this ![container_obj](https://private-user-images.githubusercontent.com/52459202/371151393-af0015a8-6ed1-402d-8a2c-c60df669ce15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTU1NjYsIm5iZiI6MTcyNzM1NTI2NiwicGF0aCI6Ii81MjQ1OTIwMi8zNzExNTEzOTMtYWYwMDE1YTgtNmVkMS00MDJkLThhMmMtYzYwZGY2NjljZTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEyNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYzcxY2FhYzdiMWI2NTk4ZGQyMDNiMWVlMDBkYzllNThhYjk5NGE1ZmNhMWZlY2ZiNzIwZjIyMDU5MzkxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dLfoIAyPIPmpXzqUwXCMRGTn4Ftnk8Wqz8niLTJG5n0) and look

I need a file not an inline attachment...

**Comment by BeckerWdf** [comment]
Sorry I made an error:
This is the correct before and after imag:
<img width="717" alt="image" src="https://github.com/user-attachments/assets/acfce77b-b97d-4ab2-8016-0c0b1eb4c6c7">

**Comment by BeckerWdf** [comment]
<img width="749" alt="image" src="https://github.com/user-attachments/assets/cb296448-3b68-48af-925a-1162fd534049">
